name = "SchoolChoice"
uuid = "be6b530c-b43c-470b-a939-67ed378dc712"
authors = ["Pedro Vergara Merino <pedro.vergaramerino@sciencespo.fr>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
